# Figurindex {-}

### Strukturell integration {-}

\@ref(fig:f1d1) - Procent med tillgång till en kontantmarginal (300, 1,000 eller 15,000 kronor) uppdelat på ålder och bakgrund.

\@ref(fig:f1d2) - Procent som ofta, ibland, eller aldrig måste avstå från aktiviteter med kompisar för att man inte har råd, uppdelat på ålder och bakgrund. 

\@ref(fig:f4-4) - Fördelning av meritvärde i årskurs 9 för unga som gick ut grundskolan 2012, uppdelat på bakgrund/generation

\@ref(fig:f4-5) - Genomsnittligt meritvärde (med 95-procentigt konfidensintervall) i årskurs 9 efter ålder vid invandring. Glidande medelvärden. Endast unga födda i Sverige eller invandrade före 15 års ålder.

\@ref(fig:f4-7) - Direktövergång till olika program på gymnasiet efter årskurs 9, elever avgångna 2012. NA=Naturprogram; SA=Samhällsprogram; Annan HSF=Annat högskoleförberedande; Yrkes=Alla icke högskoleförberedande program.

\@ref(fig:f4-8) - Andelen som påbörjat universitet eller högskola senast 2020 bland unga med svensk respektive utländsk bakgrund, per kön och vid olika betygsnivåer.

\@ref(fig:f4-9) - Andelen som tagit 60, 120 respektive 180 högskolepoäng ett givet antal terminer efter den första starten vid universitet eller högskola, uppdelat på bakgrund och kön. SVF=Svenskfödda föräldrar; UB=Utländsk bakgrund.

\@ref(fig:f4-10) - Andelen som tagit en examen ett givet antal terminer efter den första starten vid universitet eller högskola, uppdelat på bakgrund och kön. SVF=Svenskfödda föräldrar; UB=Utländsk bakgrund.

\@ref(fig:f4-11) - Andelen i födelsekohorterna 1967–1990 från olika generationer som har en universitets- eller högskoleexamen vid 30 års ålder. SVF=Svenskfödda föräldrar.

\@ref(fig:f4-12) - Andelen i födelsekohorterna 1967–1990 som har en universitets- eller högskoleexamen vid 30 års ålder, uppdelat på bakgrundsregion. Sena generation 1 exkluderad. Glidande medelvärden. SVF=Svenskfödda föräldrar.

\@ref(fig:f4-13) - Andelen i födelsekohorterna 1967–1990 från olika generationer som har en gymnasieexamen vid 29 års ålder. SVF=Svenskfödda föräldrar.

\@ref(fig:f4-14) - Sysselsättning år 2016–2019 efter svensk respektive utländsk bakgrund för dem som gick ut årskurs 9 år 2012. SVF=Svenskfödda föräldrar.

\@ref(fig:f4-15) - Sysselsättning år 2019 efter gymnasieprogram för unga med svensk respektive utländsk bakgrund som gick ut årskurs 9 år 2012. YRK=Yrkesförberedande program; HSF=Högskoleförberedande program; ea=Ej examen; Uni/HS=Universitet eller högskola.

\@ref(fig:f4-16) - Sysselsättning 2019 bland dem som var obehöriga till gymnasiet efter årskurs 9. Unga med svenskfödda föräldrar (Sv) och unga med bakgrund i olika länder/regioner (Jug=F.d. Jugoslavien; Afr=Afrika utom Nordafrika; Tur=Turkiet; M-Ö=Övriga Mellanöstern och Nordafrika; Övr Asi=Övriga Asien; Uni/HS=Universitet eller högskola.

\@ref(fig:f4-17) - Förvärvsinkomster (årsinkomster brutto, 100-tals kronor) vid 30 års ålder per kohort 1967–1989, uppdelat på generation. Glidande medelvärden. De heldragna linjerna visar medianinkomsten (percentil 50) och de streckade linjerna visar inkomsten vid percentil 25 respektive 75. Realinkomster, 2019 års värden

\@ref(fig:f4-18) - Inkomst- och utbildningsfördelningen bland unga, födda 1989, vid 30 års ålder och bland deras föräldrar. Föräldrars inkomster mätta när barnen var 23–27 år

### Social integration {-}

\@ref(fig:famtyp-orig) - Andel unga i olika familjetyper efter ursprungsgrupp

\@ref(fig:vaxbo) - Andelen unga med separerade föräldrar som bor hos båda föräldrarna ungefär lika mycket (växelvis boende), uppdelat på bakgrund

\@ref(fig:famindex) - Skillnader i olika typer av familjerelationer uppdelat på bakgrund

\@ref(fig:avg-foreign-friends) - Genomsnittlig andel vänner med utländsk bakgrund (baserad på 5 bästa vänner, så kallad person-generator) uppdelat på kön och bakgrund.

\@ref(fig:foreign-friends-context) - Andelen vänner med utländsk bakgrund uppdelat på bakgrund, kön respektive andelen utrikesfödda i skolan

\@ref(fig:foreign-friends-age) - Vänskapsintegration över ålder. Andel av fem bästa vänner från ”utgrupp”, definierat som utländsk bakgrund om man själv är av svensk bakgrund, och vice versa.

\@ref(fig:f5-10) - Andelen i olika ursprungsgrupper vars första samboende, make/maka eller registrerad partner var någon med svensk bakgrund, samma bakgrund som den egna eller med någon annan bakgrund (kohorten född 1996).

\@ref(fig:f5-11) - Andelen av män och kvinnor i olika ursprungsgrupper vars första samboende, make/maka eller registrerad partner var någon med svensk bakgrund, samma bakgrund som den egna eller med någon annan bakgrund

\@ref(fig:f5-12) - Andelen av män och kvinnor i olika ursprungsgrupper vars första samboende, make/maka eller registrerad partner var med någon med svensk bakgrund, samma bakgrund som den egna eller med någon annan bakgrund. Födelsekohorterna 1986–1996

\@ref(fig:f5-13) - Andelen av personer i olika ursprungsgrupper vars första samboende, make/maka eller registrerad partner var med någon med svensk bakgrund, samma bakgrund som den egna, samma region som den egna eller med bakgrund i annan region. Födelsekohorterna 1986–1996. Regioner: (a) Norden, (b) Östeuropa + F.d. Sovjet, (c) F.d. Jugoslavien + Albanien, (d) MENA, Afgh, Pak, (e) Syd- & Mellanamerika, (f) Afrika.

\@ref(fig:social-gender-background) - Genomsnittligt antal sociala fritidsaktiviteter per år, uppdelat på kön och bakgrund. CILS4EU våg 1.

\@ref(fig:sports) - Den genomsnittliga frekvensen av deltagande i föreningsaktiviteter i olika grupper i olika åldrar. CILS4EU våg 1–4.

\@ref(fig:club-foreign) - Medelvärde för i vilken utsträckning man träffar andra grupper (för unga med svensk bakgrund gäller det dem med utländsk bakgrund och vice versa) under föreningsaktiviteter, uppdelat på kön och bakgrund. Analysen gäller bara dem som är aktiva i föreningar. CILS4EU våg 1.

\@ref(fig:victim) - Andelen som uppger att de är utsatta för mobbning uppdelat på kön och bakgrund samt efter andel med utländsk bakgrund i skolan

\@ref(fig:f5-18) - Andelen i olika ursprungsgrupper som uppger att de utsatts för diskriminering eller orättvis behandling. ÖE=Östeuropa; ME=Mellanöstern och Nordafrika; AF=Övriga Afrika; AS=Övriga Asien.

\@ref(fig:discrimination-orig) - Andelen i olika grupper som uppger att de utsatts för dålig behandling på grund av kön, etnisk eller nationell bakgrund, ålder eller annat skäl, uppdelat på ursprungsgrupp.

\@ref(fig:discrimination-ethn) - Andelen i olika grupper som uppger att de utsatts för dålig behandling på grund av etnisk eller nationell bakgrund

\@ref(fig:f5-21) - Attityder till olika etniska grupper bland unga med svensk (övre delen) respektive utländsk bakgrund (nedre delen). Attityden till den grupp man själv tillhör har räknats bort

### Kulturell integration {-}

\@ref(fig:identification-gen) - Procentandel som anser att deras identifiering med Sverige är mycket stor, ganska stor, inte så stor respektive inte alls stor efter bakgrund

\@ref(fig:identification-orig) - Andelen som uppger olika grad av identifiering med Sverige, uppdelat på ursprungsregion och generation.

\@ref(fig:identification-age) - Förändringen mellan åldrarna 14 och 19 i identifiering med Sverige, och föräldrarnas identifiering med Sverige (F), uppdelat på bakgrund.

\@ref(fig:identification-other-age) - Förändringen mellan åldrarna 14 och 16 i identifiering med annan etnisk grupp än svensk, samt föräldrars identifiering med annan etnisk grupp (F), uppdelat på bakgrund.

\@ref(fig:identification-other-age-origin) - Identifiering med annan etnisk grupp

\@ref(fig:f6-6) - Förändringen mellan åldrarna 14 och 16 i etnisk identifiering (svensk/annan) uppdelat på bakgrund.

\@ref(fig:f6-7) - Förändringen mellan åldrarna 14 och 16 i etnisk identifiering (svensk/annan) uppdelat på ursprungsregion. CILS4EU, våg 1–3.

\@ref(fig:swedish-skills) - Medelvärde av självskattad svenska och resultat på ett svensktest efter bakgrund

\@ref(fig:religion-background) - Andelen som anger att de tillhör olika religioner (kristendom, islam, annan) eller ingen religion, uppdelat på bakgrund

\@ref(fig:religion-origin) - Religionstillhörighet efter ursprungsregion.

\@ref(fig:religion-importance-background) - Religiositet uppdelat på bakgrund. Endast de som har en religion.

\@ref(fig:religion-importance-origin) - Religiositet bland unga med utländsk bakgrund efter ursprungsregion. Endast de som har en religion

\@ref(fig:religion-importance-bgrel) - Religiositet bland kristna respektive muslimer uppdelat efter bakgrund.

\@ref(fig:f6-14) - Procentandel som som tycker att religion är inte alls viktig, inte så viktig, ganska viktig respektive mycket viktig efter bakgrund och religiös tillhörighet bland föräldrar och barn

\@ref(fig:religiosity-age) - Religiositet vid olika åldrar, uppdelat efter bakgrund och religion.

\@ref(fig:family-attitudes-genderbg) - Andelen som anger att det aldrig är OK med skilsmässa, samboende, abort respektive homosexualitet, uppdelat på bakgrund och kön.

\@ref(fig:family-attitudes-origin) - Andelen med olika bakgrund som anger att det aldrig är OK med skilsmässa, samboende, abort respektive homosexualitet.

\@ref(fig:family-attitudes-age) - Genomsnittlig andel vid 14 respektive 16 års ålder som svarat ”aldrig OK” på frågorna om samboende, skilsmässa, abort och homosexualitet. Uppdelat på bakgrund.

\@ref(fig:gender-attitudes-genderbg) - Andelen som ger ett könsstereotypt svar på frågor om mannen, kvinnan eller båda ungefär lika mycket ska ta hand om barn, laga mat, tjäna pengar och städa, uppdelat på bakgrund och kön.

\@ref(fig:gender-attitudes-origin) - Andelen i olika ursprungsgrupper som ger ett könsstereotypt svar på frågor om mannen, kvinnan eller båda ungefär lika mycket ska ta hand om barn, laga mat, tjäna pengar och städa

\@ref(fig:gender-attitudes-age) - Genomsnittlig andel i olika åldrar som ger ett könsstereotypt svar på frågor om mannen, kvinnan eller båda ungefär lika mycket ska ta hand om barn, laga mat, tjäna pengar och städa, uppdelat på bakgrund.

\@ref(fig:violence-attitudes-genderbg) - Andelen med svensk och utländsk bakgrund som anger att det är rätt för en man att gripa till våld för att försvara fru och barn, mot förolämpningar och om någon talar illa om hans familj, allt uppdelat på bakgrund och kön.

\@ref(fig:violence-attitudes-origin) - Andelen från olika ursprungsgrupper som anger att det är rätt för en man att gripa till våld för att (1) försvara fru och barn, (2) mot förolämpningar och (3) om någon talar illa om hans familj, allt uppdelat på kön.

\@ref(fig:integration-attitudes-background) - Andelen 14-åringar som instämmer i att svenskar/invandare ska behålla sin kultur respektive anpassa sig till den andra gruppen, uppdelat på generation.

### Politisk integration {-}

\@ref(fig:discuss-pol) - Andelen som diskuterar politik med sina föräldrar, uppdelat på bakgrund.

\@ref(fig:political-interest-age) - Intresse för svensk politik vid olika åldrar, uppdelat på bakgrund.

\@ref(fig:soc-engage) - Samhällsengagemang av fyra slag, uppdelat på bakgrund.

### Adaption {-}

\@ref(fig:internalising) - Internaliserande problem (nervositet, ängslighet, depression, huvudvärk, magont respektive svårt att somna), uppdelat på bakgrund och kön. Skalan går från 0 (aldrig) till 3 (ofta)

\@ref(fig:internalising-age) - Internaliserande problem i olika åldrar, uppdelat på kön och bakgrund. Värdena visar genomsnittliga svar på frågor om hur ofta man har problem med nervositet, ängslighet, depression, huvudvärk, magont och svårt att somna. Skalan går från 0 (aldrig) till 3 (ofta)

\@ref(fig:f8-3) - Andelen som uppger att de antingen vandaliserat, stulit eller burit vapen under de senaste tre månaderna, uppdelat på bakgrund och kön

\@ref(fig:f8-4) - Andelen som dricker, röker eller använder droger (har inte svarat att de ”Aldrig” gör det) och andelen som varit riktigt full någon gång de senaste tre månaderna, uppdelat på bakgrund

\@ref(fig:f8-5) - Andelen som dricker alkohol vid olika åldrar, uppdelat på bakgrund och kön.

\@ref(fig:f8-6) - Generell framtidstro vid 14 års ålder, uppdelat på bakgrund respektive kön. Andelen som instämmer i påståendet ”Jag kommer att få det bra i framtiden”.

\@ref(fig:f8-7) - Framtidstro på olika områden vid 14 års ålder, uppdelat på bakgrund. (”När du är 30 år, tror du att du kommer att …?”)

\@ref(fig:f8-8) - Livstillfredsställelse vid 14 års ålder, uppdelat på bakgrund, ursprungsregion och kön. Genomsnittligt svar på frågan ”Hur nöjd är du med ditt liv generellt?”. Svarsalternativen från 1 till 10 är uppdelade i tre kategorier.

\@ref(fig:f8-9) - Självskattad hälsa vid 14 års ålder, uppdelat på kön och bakgrund.

\@ref(fig:f8-10) - Kumulativ andel döda i olika grupper för födelsekohorter 1985–2005, för åldrarna 15 till 30. Anger hur stor andel som dött upp till och med en given ålder, i genomsnitt över kohorterna (varje kohort ges lika vikt).

